### ISSUE TITLE
displaying the name of the author

### ISSUE THREAD

**Issue by shannaverspreet** [samgielis/Hersenvulsel#5]
Will the name of the author be displayed, yes or no?
In the case of guest bloggers: will they all need their own account for their names to match? Or will I be able to publish everything and put their names there?

**Comment by samgielis** [comment]
In the sense that github allows static-content only, I would work with a static dataset of 'accounts' which contains a list of 'profiles'. A profile = [authorID, name, picture, url, tagline]. This gets uploaded to some folder on the server.

A newly-submitted article should contain a reference to this 'authorID', allowing the website to fetch and display the right author data. We could work with a 'default', where, if no authorID is provided, we post the article under some root profile like 'admin' or 'Hersenvulsel' or ...

There will be no actual accounts, as we won't be able to login people on out static website.

**Comment by samgielis** [comment]
Personally, I would include this feature because:
A. It looks nicer design-wise.
B. By including support for guest authors from scratch, we equip our website to expand more easily in the future.

**Comment by samgielis** [comment]
This issue has been resolved in the way that we've chosen to go with displaying author profiles and names with each article. This allows us to have guest posts in the future. 

Furthermore, we will build a type of 'static' author profiles where all articles by a given author will show alongside a small bio. e.g. [hersenvulsel.be/a/shannaverspreet/](hersenvulsel.be/a/shannaverspreet/).
